app/blueprints/pedidos.py
from math import ceil
from flask import Blueprint, render_template, request, jsonify
from flask_security import login_required, current_user
from app import db
# from app import utils
from app.models import (Pedido, Cupon, Filial, Segmento, Coop, Vendedor,
                        RoleUser, Role)
from sqlalchemy import text, distinct
# from sqlalchemy.sql import func
from app.utils import Log


pedidos_bp = Blueprint('pedidos', __name__)


# Select o nome do cooperado para o autocomplete do campo nome do cooperado no
# de cadastro de pedidos
@pedidos_bp.route('/autocompletenome', methods=["GET"])
def autocompletenome():
    search = request.args.get('q')
    nome = '{}%'.format(search)

    # ilike para desativar o case sensitive da consulta.
    query = Coop.query.filter(Coop.nome.ilike(nome)).all()
    results = [coop.nome for coop in query]
    return jsonify(matching_results=results)


# Select o nome do vendedor para o autocomplete do campo vendedor de cadastro
# de pedidos
@pedidos_bp.route('/autocompletevendedor', methods=["GET"])
def autocompletevendedor():
    search = request.args.get('q')
    nome = '{}%'.format(search)

    # ilike para desativar o case sensitive da consulta.
    query = Vendedor.query.filter(Vendedor.nome.ilike(nome)).all()
    results = [vendedor.nome for vendedor in query]
    print(results)
    return jsonify(matching_results=results)


def gera_cupom(valor, segmento_id, pedido):
    " Gera os cupons para concorrer a sorteios"
    valor = float(valor.replace(',', '.'))

    segmento = Segmento.query.get(segmento_id)
    if segmento.valor_cupon == 0:
        # não gera cupons
        return 0
    elif segmento.valor_cupon == 1:
        # gera apenas 1(Um) cupon
        db.session.add(Cupon(pedido=pedido))
        db.session.commit()
        return 1
    else:
        # gera cupons de acordo com o valor do pedido e o valor_cupon
        quantidade = round(valor / segmento.valor_cupon)
        for i in range(quantidade):
            db.session.add(Cupon(pedido=pedido))
        db.session.commit()
        return quantidade


@pedidos_bp.route('/pedidos')
def index():
    " Lista os ultimos 20 pedidos e um total de pedidos e valores "
    pedidos = Pedido.query.order_by(Pedido.id.desc()).limit(20).all()
    pedidos_quant = Pedido.query.count()
    pedidos_valor = db.session.query(db.func.sum(Pedido.valor)).first()
    print('\n\n\n', pedidos)
    return render_template("pedidos_index.html", pedidos=pedidos,
                           pedidos_quant=pedidos_quant,
                           pedidos_valor=pedidos_valor[0])


@pedidos_bp.route('/pedidos/new')
@login_required
def new():
    user = current_user.get_id()
    user_name = current_user.name

    # Caso o usuário for do grupo 'filial_user', só pode lançar pedido para
    # as filiais a qual pertence na tabela 'filiais_users' (FilialUser)
    if current_user.roles[0].name == 'filial_user':
        print('\n\n elaia')
        filial_id = current_user.filiais[0].id
        filiais = Filial.query.filter_by(id=filial_id).all()
    else:
        filiais = Filial.query.order_by(Filial.nome.asc()).all()

    segmentos = Segmento.query.all()
    return render_template('pedidos_form_add.html', filiais=filiais,
                           segmentos=segmentos, user_name=user_name)


@pedidos_bp.route("/pedidos/new/save", methods=["GET", "POST"])
def new_save():
    if request.method == "POST":
        dados = request.form.to_dict()
        print(dados)
        nomeCooperado = dados['nomeCooperado']  # Nome do cooperado
        nomeVendedor = dados['nomeVendedor']  # Nome do vendedor
        filial_id = dados['filial']  # Códido da filial
        segmento_id = dados['segmento']  # Segmento ex: loja, insumos, nutriçao
        valor = dados['valor']  # Valor do pedido

        Log('func new_save: nomeCooperado: {}'.format(nomeCooperado))
        Log('func new_save: nomeVendedor: {}'.format(nomeVendedor))
        Log('func new_save: filial_id: {}'.format(filial_id))
        Log('func new_save: segmento_id: {}'.format(segmento_id))
        Log('func new_save: valor: {}'.format(valor))

        cooperado = Coop.query.filter_by(nome=nomeCooperado).first()
        Log('func new_save: Coop.query: {}'.format(cooperado))
        if cooperado is None:
            Log('ERROR func new_save: Cooperado não cadastrado')
            msg = {"error": "Cooperado não cadastrado",
                   "data": (nomeCooperado,),
                   "btn_type": "button",
                   "btn_url": "",
                   "btn_label": "Voltar"}
            return render_template('pedidos_error.html', msg=msg)

        vendedor = Vendedor.query.filter_by(nome=nomeVendedor).first()
        Log('func new_save: Vendedor.query: {}'.format(vendedor))
        if vendedor is None:
            Log('ERROR func new_save: Vendedor não cadastrado')
            msg = {"error": "Vendedor não cadastrado",
                   "data": (nomeVendedor,),
                   "btn_type": "button",
                   "btn_url": "",
                   "btn_label": "Voltar"}
            return render_template('pedidos_error.html', msg=msg)

        filial = Filial.query.filter_by(id=filial_id).first()
        Log('func new_save: Filial.query: {}'.format(filial))

        # Caso o usuário pertença ao Role 'filial_user' então é pedido tirado
        # nas lojas, e recebe importado=1
        # Caso não, é pedido tirado na feira e recebe importado=0
        if current_user.roles[0].name == 'filial_user':
            importado = '1'
        else:
            importado = '0'
        Log('func new_save: importado: {}'.format(importado))

        # Verificando se já existe um pedido igual no banco de dados
        checa = Pedido.query.filter_by(
            coop=cooperado,
            vendedor=vendedor,
            valor=valor,
            filial=filial).first()
        Log('func new_save: checa pedido: {}'.format(checa))
        if checa is not None:
            Log('ERROR func new_save: Pedido já cadastrado')
            msg = {"error": "pedido já cadastrado (duplicado)",
                   "data": ("Cooperado: {}".format(nomeCooperado),
                            "Vendedor: {}".format(nomeVendedor),
                            "Filial: {}".format(filial),
                            "Valor: {}".format(valor)),
                   "btn_type": "button",
                   "btn_url": "",
                   "btn_label": "Voltar"}
            return render_template('pedidos_error.html', msg=msg)
            # return render_template('erro_pedido_duplicado.html',pedido=checa)

        # Incluindo o pedido no banco de dados usando SqlAlchemy
        pedido = Pedido(
            valor=valor,
            importado=importado,
            user=current_user,
            segmento_id=segmento_id,
            vendedor=vendedor,
            coop=cooperado,
            filial=filial)
        Log('func new_save: pedido: {}'.format(pedido))
        db.session.add(pedido)
        Log('func new_save: pedido add: {}'.format(pedido))
        db.session.commit()
        Log('func new_save: pedido add commit: {}'.format(pedido))

        # gerando cupons
        # gera os cupons, e já adiciona no banco de dados e faz o commit
        cupons = gera_cupom(
            valor=valor, segmento_id=segmento_id, pedido=pedido)
        Log('func new_save: gera cupons: {}\n'.format(cupons))

        # Formata o numero do pedido para ficar com 4 digitos
        if pedido.id < 1000:
            idpedido = '{:0>4}'.format(pedido.id)
        else:
            idpedido = pedido.id

        # return "Pedido: {}<br> Cupons: {}".format(pedido, cupons)
        return render_template("pedidos_saved.html", idpedido=idpedido,
                               cupons=cupons)


@pedidos_bp.route('/pedidos/list')
@pedidos_bp.route('/pedidos/list/<int:page>')
def list(page=None):
    " Lista todos os pedidos em paginas (paginate) "

    # quantidade de linhas por pagina
    PER_PAGE = 5

    if not page:
        page = 0

    # pagina anterior
    if page <= 1:
        left = None
    if page > 1:
        left = page - 1

    pedidos_quant = Pedido.query.count()
    if pedidos_quant > PER_PAGE:
        pages = range(1, ceil(pedidos_quant / PER_PAGE) + 1)
    else:
        pages = (1)

    # proxima pagina
    if len(pages) == page:
        right = None
    else:
        right = page + 1

    # pega os pedidos
    if page >= 1:
        pedidos = Pedido.query.order_by(Pedido.id.desc())\
            .limit(PER_PAGE)\
            .offset(PER_PAGE * page - PER_PAGE).all()
    else:
        pedidos = Pedido.query.order_by(
            Pedido.id.desc()).limit(PER_PAGE).offset(0).all()
    print('\n\n\n', pedidos, '\n\n')
    return render_template("pedidos_list.html", pedidos=pedidos, page=page,
                           left=left, right=right, pages=pages)

app/templates/layout.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CamdaExpo Evento CAMDA">
    <meta name="author" content="Carlos Henrique Marques da Cunha Filho">

    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/favico32.jpeg') }}" />

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui-1.12.1.css') }}">

    <title>{% block title %} {{title or "Evento CAMDA"}} {% endblock %}</title>

  </head>

  <script src="{{ url_for('static', filename='js/jquery-3.4.1.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-ui-1.12.1.js') }}"></script>


  <body>
    {% block navbar %}
    {% endblock %}
    <br />
    <div class="container" id="principal" >
      {% block body_content %}
      {% endblock %}
    </div>
  </body>

  <script>
  // $(document).ready(function() {
  //     console.log('read: Pagina carregada');
  //     jQuery("#principal").show();
  //     // jQuery("#menuprincipal").show();
  // }).delay(200);
  </script>

</html>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand btn border-primary my-2 my-sm-0 text-primary" href="{{ url_for('pedidos.index') }}">
    {% block nav_title %} {{ title or "Evento CAMDA" }} {% endblock %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == '/pedidos' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('pedidos.index')}}">Home<span class="sr-only"></span></a>
      </li>
      <!-- <li class="nav-item {% if request.path == '/pedidos/new' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('pedidos.new')}}">Novo</a>
      </li> -->
      <li class="nav-item dropdown {% if '/pedidos/' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="{{ url_for('pedidos.new')}}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Pedidos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ url_for('pedidos.new')}}">Novo</a>
          <a class="dropdown-item" href="{{ url_for('pedidos.list')}}">Listar pedidos</a>
          <!-- <div class="dropdown-divider"></div> -->
          <!-- <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <button class="btn btn-outline-primary" type="submit" formaction="{{ url_for('admin.index') }}">Admin</button>
    </form>
  </div>
</nav>

app/templates/pedidos_error.html
{% extends "layout.html" %}

{% block body_content %}

<form class="border border-danger p-5" style="text-transform:uppercase">

<div class="row alert alert-danger">
    <strong><div class="col h2">{{msg['error']}}</div></strong>
</div>

{% for data in msg['data'] %}
<div class="row alert alert-warning text-dark m-0">
    <strong><div class="col h2">{{data}}</div></strong>
</div>
{% endfor %}
<br />
{% if msg['btn_type'] == "button" %}
  <input type="button" autofocus class="btn btn-lg btn-primary" value="{{msg['btn_label']}}" onClick="history.go(-1)">
{% elif msg['btn_type'] == "submit" %}
  <button type="submit" autofocus class="btn btn-lg btn-primary" formaction="{{ url_for(msg['btn_url']) }}">{{msg['btn_label']}}</button>
{% endif %}

</form>

{% endblock %}

app/templates/pedidos_form_add.html
{% extends "layout.html" %}

{#% block title %} {{ title or "Evento CAMDA" }} {% endblock %#}

{% block navbar %} {% include "navbar.html" %} {% endblock %}

{% block body_content %}

<script src="{{ url_for('static', filename='js/jquery.validate-1.19.1.js') }}"></script>
<script type="text/javascript">
$(function() {
   $("#nomeCooperado").autocomplete({
       source:function(request, response) {
           $.getJSON("{{url_for('pedidos.autocompletenome')}}",{
               q: request.term, // in flask, "q" will be the argument to look for using request.args
           }, function(data) {
               response(data.matching_results); // matching_results from jsonify
           });
       },
       minLength: 4,
       // select: function(event, ui) {
       //     console.log(ui.item.value); // not in your question, but might help later
       // }
   });
})

$(function() {
   $("#nomeVendedor").autocomplete({
       source:function(request, response) {
           $.getJSON("{{url_for('pedidos.autocompletevendedor')}}",{
               q: request.term, // in flask, "q" will be the argument to look for using request.args
           }, function(data) {
               response(data.matching_results); // matching_results from jsonify
           });
       },
       minLength: 4,
       // select: function(event, ui) {
       //     console.log(ui.item.value); // not in your question, but might help later
       // }
   });
})


$( document ).ready( function () {
$("#form_pedido").validate({
    rules:{
        nomeCooperado:{
            required:true,
            minlength:8
        },
        nomeVendedor:{
            required:true,
            minlength:8
        },
        valor:{
            required:true,
            number:true
        }
    },
    messages:{
        nomeCooperado:{
            required:"Digite o nome do cooperado",
            minlength:"O nome do cooperado está muito curto"
        },
        nomeVendedor:{
            required:"Digite o nome do vendedor",
            minlength:"O nome do vendedor está muito curto"
        },
        valor:{
            required:"Digite o valor",
            number:"Digite um valor como 1000,00"
        }
    }

});
});
</script>
  <div class="ui-widget">
  <form class="include" method="post" id="form_pedido" action="{{ url_for('pedidos.new_save') }}">

    <div class="form-group">
        <label for="nomeCooperado">Cooperado</label>
        <input type="text" class="form-control" id="nomeCooperado" name="nomeCooperado" placeholder="Nome do coopedado" style="text-transform:uppercase" autofocus>
    </div>
    <div class="form-group">
        <label for="nomeVendedor">Vendedor</label>
        <input type="text" class="form-control" id="nomeVendedor" name="nomeVendedor" placeholder="Nome do vendedor" style="text-transform:uppercase">
    </div>
    <div class="form-group">
      <label for="filial">Filial</label>
      <select class="form-control" id="filial" name="filial">
        {% for filial in filiais %} <option value="{{filial.id}}">{{filial.numero}} - {{filial.nome}}</option> {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="segmento">Segmento</label>
      <select class="form-control" id="segmento" name="segmento">
        {% for segmento in segmentos %} <option value="{{segmento.id}}">{{segmento.nome}}</option> {% endfor %}
      </select>
    </div>
    <div class="form-group">
        <label for="valor">Valor</label>
        <input type="number" class="form-control" id="valor" name="valor" placeholder="R$ 0,00">
    </div>
     <br />
     <br />
     <input class="btn btn-lg btn-primary" id="salvar" type="submit" value="Salvar" />
   </form>
 </div>

{% endblock %}

app/templates/pedidos_index.html
{% extends "layout.html" %}

{% block navbar %} {% include "navbar.html" %} {% endblock %}

{% block body_content %}

<div class="row">
  <div class="col">
    <table class="table h3  table-borderless border border-info">
      <thead class="border border-info">
       <tr>
         <th colspan="2" scope="col">TOTAL DE PEDIDOS</th>
       </tr>
       </thead>
      <tr class="border border-info">
        <td>QUANTIDADE: {{pedidos_quant}}</td>
      </tr>
      <tr class="border border-info">
        <td>VALOR: R$ {{pedidos_valor}}</td>
      </tr>
    </table>
  </div>
  <div class="col-5"></div>
</div>
<br />

<table class="table h6 table-borderless border border-info">
  <thead class="border border-info">
   <tr>
     <th colspan="3" scope="col" class="h4">ÚLTIMOS PEDIDOS</th>
   </tr>
   <tr class="h5">
     <th scope="col">COOPERADO</th>
     <th scope="col">FILIAL</th>
     <th scope="col">VALOR</th>
   </tr>
   </thead>
{% for p in pedidos %}
  <tr class="border border-info">
    <td>{{p.coop}}</td>
    <td>{{p.filial}}</td>
    <!-- <td>R$ {{p.valor}}</td> -->
    <td>R$ {{ p.valor|replace('.', ','|safe) }}</td>
  </tr>
{% endfor %}

{% endblock %}

app/templates/pedidos_list.html
{% extends "layout.html" %}

{% block navbar %} {% include "navbar.html" %} {% endblock %}

{% block body_content %}
<table class="table h6 table-borderless border border-info">
  <thead class="border border-primary">
   <tr>
       <th colspan="4" scope="col" class="h4">LISTA DE PEDIDOS</th>
   </tr>
   <tr>
     <th scope="col">NUMERO</th>
     <th scope="col">COOPERADO</th>
     <th scope="col">FILIAL</th>
     <th scope="col">VALOR</th>
   </tr>
   </thead>
   {% for p in pedidos %}
   <tr class="border border-primary">
     <td>{{p.id}}</td>
     <td>{{p.coop}}</td>
     <td>{{p.filial}}</td>
     <td>R$ {{p.valor|replace('.', ','|safe)}}</td>
    </tr>
    {% endfor %}
</table>

<!-- Paginação -->
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if left %}
      <li class="page-item"><a class="page-link" href="{{left}}"> < </a></li>
    {% endif %}

    {% for p in pages%}

      {% if p == 1 %}
        <li class="page-item"><a class="page-link" href="{{ url_for('pedidos.list')}}"> {{p}} </a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for('pedidos.list')}}/{{p}}"> {{p}} </a></li>
      {% endif %}

    {% endfor %}

    {% if right %}
      <li class="page-item"><a class="page-link" href="{{ url_for('pedidos.list')}}/{{right}}"> > </a></li>
    {% endif %}

  </ul>
</nav>

{% endblock %}

app/templates/pedidos_saved.html
{% extends "layout.html" %}
{% block body_content %}

<form class="border border-success p-5">

<div class="row alert alert-success ">
    <div class="col"><h1>Pedido cadastrado com sucesso</h1></div>
</div>
<br />
<div class="row">
  <div class="col">
    <h3>Nº do pedido {{idpedidos}}</h3>
  </div>
</div>

    {% if cupons > 0 %}
     <div class="row">
        <div class="col">
            <h3>Esse pedido gerou {{cupons}} cupons</h3>
        </div>
    </div>
    {% else %}
    <div class="row">
       <div class="col">
           <h3>Esse pedido não gerou cupons</h3>
       </div>
   </div>
   {% endif %}

<br />
<br />
    <div class="col">
        <button type="submit" autofocus class="btn btn-lg btn-primary" formaction="{{ url_for('pedidos.new') }}">OK</button>
    </div>
</form>

{% endblock %}